language: python
python:
  - "3.6"
  - "3.7-dev"
services:
  - redis-server
install:
  - pip install -r requirements.txt
script:
  - export EFUTURE_CONFIG=`pwd`/config-example.json
  - python -m unittest discover -v
