language: python
python:
  - "3.6"
  - "3.7-dev"
services:
  - redis-server
env:
  EFUTURE_CONFIG=`pwd`/config-example.json
install:
  pip install -r requirements.txt
script:
  python -m unittest discover -v